In [ ]:
!nvidia-smi

Sun Oct 16 13:53:53 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

1.12.1+cu113


In [ ]:
#torch rand distribution 0-1
n = torch.rand(5,4,5)

In [ ]:
n

tensor([[[0.0975, 0.0405, 0.7503, 0.5726, 0.1440],
         [0.6475, 0.0513, 0.8773, 0.0425, 0.5532],
         [0.6829, 0.8788, 0.2952, 0.5665, 0.4604],
         [0.4042, 0.8695, 0.6164, 0.3985, 0.9984]],

        [[0.5201, 0.2463, 0.7638, 0.6277, 0.0969],
         [0.2755, 0.6954, 0.8538, 0.0120, 0.0978],
         [0.7425, 0.2090, 0.9336, 0.5537, 0.7423],
         [0.3825, 0.4377, 0.3247, 0.8933, 0.4682]],

        [[0.0463, 0.9908, 0.8739, 0.1045, 0.8834],
         [0.6413, 0.4051, 0.9016, 0.4984, 0.6302],
         [0.8664, 0.1140, 0.0244, 0.8588, 0.1589],
         [0.2788, 0.0195, 0.9898, 0.7728, 0.9693]]])

In [ ]:
n.ndim

3

In [ ]:
k = torch.ones(1,2)

In [ ]:
k

tensor([[1., 1.]])

In [ ]:
k = torch.arange(1,11,2)
k

tensor([1, 3, 5, 7, 9])

In [ ]:
##Important##
p = torch.zeros_like(k)
p

tensor([0, 0, 0, 0, 0])

In [ ]:
float_32 = torch.tensor(range(1,6),dtype=torch.float32)
float_32

tensor([1., 2., 3., 4., 5.])

In [ ]:
float_16 = float_32.type(torch.float16)
float_16


tensor([1., 2., 3., 4., 5.], dtype=torch.float16)

In [ ]:
float_16.shape

torch.Size([5])

In [ ]:
a = float_32 * float_16
a.dtype

torch.float32

In [ ]:
x_rand = torch.randn(size = (224,224,3))
#now rearrange the dimensions
x_new = x_rand.permute(dims=(2,0,1))
print(x_rand.shape)
print(x_new.shape)
# it shares the same memory/variable.

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [ ]:
x = torch.rand(size = (1,1,4))
x

tensor([[[0.3649, 0.2141, 0.6881, 0.5286]]])

In [ ]:
x = x.squeeze()
x

tensor([0.3649, 0.2141, 0.6881, 0.5286])

In [ ]:
 x = x.unsqueeze(dim=0)
 x,x.shape
 # 0 adds dimensions to the front , 1 adds dimensions to the back
 #interpret fromt the equations.

(tensor([[[0.3649, 0.2141, 0.6881, 0.5286]]]), torch.Size([1, 1, 4]))

In [3]:
#random seed is not true randomness
import torch

In [4]:
Rand_seed = 42
torch.manual_seed(Rand_seed)
a = torch.rand(3,4)
b = torch.rand(3,4)

print(a)
print(b)
print(a == b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [8]:
#But if we add an extra random seed in between a and b
Rand_seed = 1
torch.manual_seed(Rand_seed)
a = torch.rand(3,4)
torch.manual_seed(Rand_seed)
b = torch.rand(3,4)
print(a)
print(b)
print(a == b)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [9]:
#so random seed works only for a single following random command
#now trying the other method

In [10]:
Rand_seed = 1
torch.manual_seed(Rand_seed)
a = torch.rand(3,4)
torch.manual_seed(Rand_seed)
b = torch.rand(3,4)
c = torch.rand(3,4)
print(a)
print(b)
print(c)
print(a == b)
print(b == c)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.6826, 0.3051, 0.4635, 0.4550],
        [0.5725, 0.4980, 0.9371, 0.6556],
        [0.3138, 0.1980, 0.4162, 0.2843]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [11]:
# but what if we introduce a new seed in between b,c too

In [12]:
Rand_seed = 1
torch.manual_seed(Rand_seed)
a = torch.rand(3,4)
torch.manual_seed(Rand_seed)
b = torch.rand(3,4)
torch.manual_seed(Rand_seed)
c = torch.rand(3,4)
print(a)
print(b)
print(c)
print(a == b)
print(b == c)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [13]:
#so it's done now and it's clear

In [14]:
#Accessing A GPU's

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
!nvidia-smi

Fri Oct 21 06:21:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
#putting tensor in the GPU, for faster computations

In [8]:
t = torch.tensor([1,2,3])
t.device

device(type='cpu')

In [9]:
device

'cuda'

In [13]:
t_gpu = t.to(device)
t_gpu

tensor([1, 2, 3], device='cuda:0')

In [14]:
t_return = t.cpu()
t_return #Important

tensor([1, 2, 3])

In [15]:
t_return.numpy()

array([1, 2, 3])

In [17]:
#Excercise 
#5.
Rand_seed = 1234
torch.cuda.manual_seed(Rand_seed)

In [23]:
Rand_seed = 42
torch.cuda.manual_seed(Rand_seed)
a = torch.rand(3,4,device='cuda')
#a.to(device)
#torch.cuda.manual_seed(Rand_seed)
b = torch.rand(3,4,device='cuda')
#b.to(device)
print(a)
print(b)
print(a==b)

tensor([[0.6130, 0.0101, 0.3984, 0.0403],
        [0.1563, 0.4825, 0.7362, 0.4060],
        [0.5189, 0.2867, 0.2416, 0.9228]], device='cuda:0')
tensor([[0.9877, 0.1289, 0.5621, 0.5221],
        [0.7445, 0.5955, 0.9647, 0.8979],
        [0.7730, 0.6681, 0.5462, 0.5071]], device='cuda:0')
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]], device='cuda:0')


In [24]:
# random seed works similiar to as in CPU , just use device in rand so, it will create the tensor in the Gpu

In [26]:
c = torch.matmul(a,b.T)
c

tensor([[0.8517, 0.8829, 0.7186],
        [0.8424, 1.4784, 1.0512],
        [1.1671, 1.6187, 1.1926]], device='cuda:0')

In [27]:
d = torch.argmax(c)

In [28]:
c.shape,d

(torch.Size([3, 3]), tensor(7, device='cuda:0'))

In [33]:
c = c.squeeze()
c

tensor([[0.8517, 0.8829, 0.7186],
        [0.8424, 1.4784, 1.0512],
        [1.1671, 1.6187, 1.1926]], device='cuda:0')

In [34]:
c.shape

torch.Size([3, 3])

In [42]:
c = c.flatten()
print(f"max",{c[d]})

max {tensor(1.6187, device='cuda:0')}


In [44]:
d = torch.argmin(c)
c[d]

tensor(0.7186, device='cuda:0')

In [51]:
#10th exercise
rt = torch.rand(1,1,1,10)
print(rt,rt.shape)
print("now\n")
rt = torch.squeeze(rt,0)
print(rt,rt.shape)
print("now\n")
rt = torch.squeeze(rt,0)
print(rt,rt.shape)
print("now\n")
rt = torch.squeeze(rt,0)
print(rt,rt.shape)

tensor([[[[0.8045, 0.0688, 0.2405, 0.5678, 0.0188, 0.3875, 0.6440, 0.2094,
           0.3048, 0.9919]]]]) torch.Size([1, 1, 1, 10])
now

tensor([[[0.8045, 0.0688, 0.2405, 0.5678, 0.0188, 0.3875, 0.6440, 0.2094,
          0.3048, 0.9919]]]) torch.Size([1, 1, 10])
now

tensor([[0.8045, 0.0688, 0.2405, 0.5678, 0.0188, 0.3875, 0.6440, 0.2094, 0.3048,
         0.9919]]) torch.Size([1, 10])
now

tensor([0.8045, 0.0688, 0.2405, 0.5678, 0.0188, 0.3875, 0.6440, 0.2094, 0.3048,
        0.9919]) torch.Size([10])
