<a href="https://colab.research.google.com/github/baveet256/Pytorch-DL/blob/main/Pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import nn
import matplotlib.pyplot as plt
torch.__version__

'1.12.1+cu113'

In [ ]:
m = 0.7
b = 0.3
x = torch.arange(0,1,0.02)
print(x.shape)

torch.Size([50])


In [ ]:
x = x.unsqueeze(dim=1)
print(x.shape)

torch.Size([50, 1])


In [ ]:
x

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800],
        [0.2000],
        [0.2200],
        [0.2400],
        [0.2600],
        [0.2800],
        [0.3000],
        [0.3200],
        [0.3400],
        [0.3600],
        [0.3800],
        [0.4000],
        [0.4200],
        [0.4400],
        [0.4600],
        [0.4800],
        [0.5000],
        [0.5200],
        [0.5400],
        [0.5600],
        [0.5800],
        [0.6000],
        [0.6200],
        [0.6400],
        [0.6600],
        [0.6800],
        [0.7000],
        [0.7200],
        [0.7400],
        [0.7600],
        [0.7800],
        [0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

In [ ]:
y = m*x + b
y.shape

torch.Size([50, 1])

In [ ]:
x[:6] # 0 to 6(index 5)


tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000]])

In [ ]:
x[6:] #6 to end(index 6 to end)

tensor([[0.1200],
        [0.1400],
        [0.1600],
        [0.1800],
        [0.2000],
        [0.2200],
        [0.2400],
        [0.2600],
        [0.2800],
        [0.3000],
        [0.3200],
        [0.3400],
        [0.3600],
        [0.3800],
        [0.4000],
        [0.4200],
        [0.4400],
        [0.4600],
        [0.4800],
        [0.5000],
        [0.5200],
        [0.5400],
        [0.5600],
        [0.5800],
        [0.6000],
        [0.6200],
        [0.6400],
        [0.6600],
        [0.6800],
        [0.7000],
        [0.7200],
        [0.7400],
        [0.7600],
        [0.7800],
        [0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

In [ ]:
  ## now splitting the data x,y manually
t = int(0.8*len(y)) 
x_train,y_train = x[:t],y[:t]
x_test,y_test = x[t:],y[t:]
len(x_train),len(y_train),len(x_test),len(y_test)

(40, 40, 10, 10)

In [ ]:
#model
from torch import nn
class Linearmodel(nn.Module):

  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
    self.bias =  nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
  
  def forward(self,x:torch.tensor):
    return self.weights*x + self.bias
 


In [ ]:
#train
torch.manual_seed(42)
model = Linearmodel()


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True), Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [ ]:
model.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [ ]:
m,b

(0.7, 0.3)

In [ ]:
#training and setting up the model
loss = torch.nn.L1Loss()
optimizer = torch.optim.SGD(params=model.parameters(), lr = 0.01)

In [ ]:
epochs = 100
for epoch in range(epochs):
  #train mode
  model.train()
  #forward pass
  y_pred = model(x_train)
  #loss
  lfunc = loss(y_pred,y_train)
  print(f"loss :{lfunc}")
  #zero
  optimizer.zero_grad()
  #back propagate
  lfunc.backward() 
  #step function
  optimizer.step()
  ## testing
  model.eval()
  with torch.inference_mode():
    #forward pass
    y_pred_test = model(x_test)
    #loss calculation
    test_loss = loss(y_pred_test,y_test)
  if epoch%10 == 0 :
    print(f"Epoch:{epoch} | loss:{lfunc} | test_loss:{test_loss}")
    print(model.state_dict())




loss :0.31288138031959534
Epoch:0 | loss:0.31288138031959534 | test_loss:0.48106518387794495
OrderedDict([('weights', tensor([0.3406])), ('bias', tensor([0.1388]))])
loss :0.3013603389263153
loss :0.28983935713768005
loss :0.2783183455467224
loss :0.26679736375808716
loss :0.2552763521671295
loss :0.24375534057617188
loss :0.23223432898521423
loss :0.22071333229541779
loss :0.20919232070446014
loss :0.1976713240146637
Epoch:10 | loss:0.1976713240146637 | test_loss:0.3463551998138428
OrderedDict([('weights', tensor([0.3796])), ('bias', tensor([0.2388]))])
loss :0.18615034222602844
loss :0.1746293306350708
loss :0.16310831904411316
loss :0.1515873372554779
loss :0.14006635546684265
loss :0.1285453587770462
loss :0.11702437698841095
loss :0.1060912236571312
loss :0.09681284427642822
loss :0.08908725529909134
Epoch:20 | loss:0.08908725529909134 | test_loss:0.21729660034179688
OrderedDict([('weights', tensor([0.4184])), ('bias', tensor([0.3333]))])
loss :0.08227583020925522
loss :0.07638873

In [ ]:
model.state_dict() 

OrderedDict([('weights', tensor([0.5784])), ('bias', tensor([0.3513]))])

In [ ]:
# over 1500 epochs we reached an accurate value

In [ ]:
with torch.inference_mode():
  y_preds_new = model(x_test)
y_preds_new   

tensor([[0.8141],
        [0.8256],
        [0.8372],
        [0.8488],
        [0.8603],
        [0.8719],
        [0.8835],
        [0.8950],
        [0.9066],
        [0.9182]])

In [ ]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [ ]:
#Saving the model
from pathlib import Path
# make directory
model_path = Path('models')
model_path.mkdir(parents=True,exist_ok=True)
# saving name, path
model_name = "Pytorch_model_1.pth"
model_save_path = model_path / model_name
print('model saved')
torch.save(model.state_dict(),model_save_path)

model saved


#load the model

In [ ]:
loaded_model = Linearmodel()
# load the saved parameters in the new abstract of the Linearmodel
loaded_model.load_state_dict(torch.load(model_save_path))

<All keys matched successfully>

In [ ]:
 loaded_model.state_dict()

OrderedDict([('weights', tensor([0.5784])), ('bias', tensor([0.3513]))])